data:
  category_csv: ../data/category.csv
  test_csv: ../data/test/test_input.csv
  debug: false

model:
  name: kobart
  pretrained_model_name_or_path : "./results/save/kobart_10epoch" #'./results/test_checkpoint'

pred:
  batch_size: 16
  threshold: 0.5
  submission_csv: './results/save/kobart_10epoch/submission.csv'

  device: "cuda:0"
