data:
  category_csv: ../data/category.csv
  test_csv: ../data/test/test_input.csv
  debug: false

model:
  pretrained_model_name_or_path : "./results/save/kobart_3epoch"

pred:
  # method: argmax
  # method: prob_threshold
  method: auto_ratio_threshold
  # method: auto_prob_threshold

  batch_size: 16
  threshold: 0.5
  submission_csv: './results/save/kobart_3epoch/submission.csv'

  device: "cuda:0"
