data:
  category_csv: ../data/category.csv
  test_csv: ../data/test/test_input.csv
  debug: false

model:
  pretrained_model_name_or_path : './results/test_checkpoint'

pred:
  batch_size: 1
  threshold: 0.5
  submission_csv: './results/ctest_checkpoint/submission.csv'

  device: "cpu" # "cuda:0"
