data:
  path: ../data
  save_tokenized_set: KoPatElectra_base # baseline
  train: ../data/train
  category_csv: ../data/category.csv
  train_csv: ../data/train/train.csv

  val_size: 0.05
  split_seed: 42
  debug: false

model:
  pretrained_model_name_or_path : "./KIPIKorPatELECTRA/KorPatELECTRA/PT" # 'monologg/koelectra-small-v3-discriminator'
  num_labels: 564

train:
  seed: 42
  deterministic: False
  gpu_id: "0"
  
  optim: adamw_torch
  epochs: 100
  batch_size: 1
  learning_rate: 0.00005
  warmup_steps: 200
  early_stop_patience: 5

  output_dir: './results'
  save_total_limit: 3
  report_to: []

  loss:
    name: FocalLoss
    params:
      gamma: 2
      pos_weight: 564
