name: patent
channels:
  - defaults
dependencies:
  - python=3.10.12
  - tensorboardX
  - pip:
    - omegaconf
    - pandas
    - torch
    - datasets
    - transformers==4.35.0
    - accelerate
    - scikit-learn
