name: patent
channels:
  - defaults
dependencies:
  - python=3.10.12
  - tensorboardX
  - pip:
    - omegaconf
    - pandas
    - torch
    - datasets
    - transformers
    - peft
    - accelerate
    - scikit-learn
    - imbalanced-learn
    - graphviz
  - torchview
